name: Build EXE for Client and Server

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**.py'
  pull_request:
    paths:
      - 'src/**.py'

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 watchdog tqdm

      - name: Compile Client to EXE
        run: |
          pyinstaller --onefile --windowed src/client/app.py --name FTClient

      - name: Compile Server to EXE
        run: |
          pyinstaller --onefile src/server/server.py --name FTServer

      - name: Upload EXEs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            dist/FTClient.exe
            dist/FTServer.exe
